services:
  web:
#    image: paper-trading:latest
    build: .
    ports:
      - "80:5000"
    depends_on:
      db:
        condition: service_healthy

    environment:
      TZ: "America/New_York"

    command: [ "python3", "app.py", "0.0.0.0"]
#    command: [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
#    command: [ "sleep", "600"]

  db:
    image: postgres:15.5-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      TZ: "America/New_York"
    volumes:
      - "C:/Users/masou/Code/Database/paper-trading:/var/lib/postgresql/"
      - "C:/Users/masou/Code/Database/paper-trading/data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "15432:5432"